// --- START PUZZLE DATA ---
export const puzzles = [
    // Originales
    { theme: "Colores", words: ["ROJO", "AZUL", "VERDE", "AMARILLO", "NARANJA", "VIOLETA", "BLANCO", "NEGRO", "TURQUESA", "MAGENTA"], secret: "EL SABER NO OCUPA LUGAR" },
    { theme: "Frutas", words: ["MANZANA", "PLATANO", "FRESA", "NARANJA", "UVA", "PERA", "LIMON", "SANDIA", "MELOCOTON", "KIWI"], secret: "A BUEN HAMBRE NO HAY PAN DURO" },
    { theme: "Animales", words: ["VACA", "CERDO", "CABALLO", "OVEJA", "GALLINA", "PATO", "CONEJO", "TORO", "ELEFANTE", "JIRAFA"], secret: "MAS VALE PAJARO EN MANO" },
    { theme: "Cuerpo Humano", words: ["CABEZA", "BRAZO", "PIERNA", "MANO", "OJO", "BOCA", "NARIZ", "OREJA", "HOMBRO", "RODILLA"], secret: "OJOS QUE NO VEN CORAZON QUE NO SIENTE" },
    
    // 50 Nuevos Puzzles
    { theme: "El Espacio", words: ["PLANETA", "ESTRELLA", "GALAXIA", "COMETA", "LUNA", "SOL", "NEBULOSA", "ASTEROIDE", "ORBITA", "COHETE"], secret: "DE OTRO MUNDO" },
    { theme: "Instrumentos Musicales", words: ["GUITARRA", "PIANO", "VIOLIN", "TROMPETA", "BATERIA", "FLAUTA", "SAXOFON", "ARPA", "BAJO", "CLARINETE"], secret: "LA MUSICA AMANSA A LAS FIERAS" },
    { theme: "Deportes", words: ["FUTBOL", "BALONCESTO", "TENIS", "NATACION", "ATLETISMO", "BOXEO", "CICLISMO", "GOLF", "VOLEIBOL", "ESGRIMA"], secret: "LO IMPORTANTE ES PARTICIPAR" },
    { theme: "Mobiliario", words: ["SILLA", "MESA", "CAMA", "ARMARIO", "SOFA", "ESTANTERIA", "ESCRITORIO", "COMODA", "VITRINA", "TABURETE"], secret: "CADA COSA EN SU LUGAR" },
    { theme: "Profesiones", words: ["MEDICO", "PROFESOR", "BOMBERO", "POLICIA", "INGENIERO", "ABOGADO", "COCINERO", "PERIODISTA", "CARPINTERO", "PINTOR"], secret: "ZAPATERO A TUS ZAPATOS" },
    { theme: "Países de Europa", words: ["ESPAÑA", "FRANCIA", "ITALIA", "ALEMANIA", "PORTUGAL", "GRECIA", "SUECIA", "NORUEGA", "FINLANDIA", "POLONIA"], secret: "TODOS LOS CAMINOS LLEVAN A ROMA" },
    { theme: "Herramientas", words: ["MARTILLO", "BROCHA", "SIERRA", "ALICATES", "LLAVE", "TALADRO", "TORNILLO", "CLAVO", "CINCEL", "ESPATULA"], secret: "QUIEN TIENE UN OFICIO TIENE UN BENEFICIO" },
    { theme: "En la Cocina", words: ["CUCHILLO", "TENEDOR", "CUCHARA", "PLATO", "VASO", "SARTEN", "OLLA", "HORNO", "NEVERA", "FUEGO"], secret: "A FUEGO LENTO" },
    { theme: "Fenómenos Meteorológicos", words: ["LLUVIA", "NIEVE", "VIENTO", "TORMENTA", "GRANIZO", "NIEBLA", "HURACAN", "TORNADO", "ARCOIRIS", "RAYO"], secret: "DESPUES DE LA TEMPESTAD VIENE LA CALMA" },
    { theme: "Partes de un Coche", words: ["MOTOR", "RUEDA", "VOLANTE", "FRENO", "ASIENTO", "PUERTA", "VENTANA", "MALETERO", "FARO", "PARACHOQUES"], secret: "SOBRE RUEDAS" },
    { theme: "Flores", words: ["ROSA", "CLAVEL", "MARGARITA", "TULIPAN", "GIRASOL", "LIRIO", "ORQUIDEA", "JAZMIN", "VIOLETA", "AMAPOLA"], secret: "LA PRIMAVERA LA SANGRE ALTERA" },
    { theme: "Ropa", words: ["CAMISETA", "PANTALON", "VESTIDO", "FALDA", "CHAQUETA", "ABRIGO", "SOMBRERO", "ZAPATOS", "GUANTES", "BUFANDA"], secret: "EL HABITO NO HACE AL MONJE" },
    { theme: "Árboles", words: ["ROBLE", "PINO", "CAOBA", "CEDRO", "ABETO", "OLIVO", "ALMENDRO", "CEREZO", "NOGAL", "CASTAÑO"], secret: "ARBOL QUE NACE TORCIDO JAMAS SU TRONCO ENDEREZA" },
    { theme: "Verduras", words: ["TOMATE", "LECHUGA", "ZANAHORIA", "PATATA", "CEBOLLA", "PIMIENTO", "ESPINACA", "BROCOLI", "CALABAZA", "PEPINO"], secret: "SANO COMO UNA MANZANA" },
    { theme: "Capitales del Mundo", words: ["MADRID", "PARIS", "LONDRES", "ROMA", "BERLIN", "LISBOA", "ATENAS", "MOSCU", "TOKIO", "PEKIN"], secret: "PREGUNTANDO SE LLEGA A ROMA" },
    { theme: "Elementos Químicos", words: ["HIDROGENO", "HELIO", "OXIGENO", "CARBONO", "HIERRO", "ORO", "PLATA", "COBRE", "SODIO", "POTASIO"], secret: "LA FORMULA SECRETA" },
    { theme: "Figuras Geométricas", words: ["CIRCULO", "CUADRAD", "TRIANGULO", "RECTANGULO", "ROMBO", "PENTAGONO", "HEXAGONO", "OVALO", "CUBO", "ESFERA"], secret: "TODO ENCAJA" },
    { theme: "Continentes", words: ["ASIA", "AFRICA", "EUROPA", "AMERICA", "OCEANIA", "ANTARTIDA", "NORTE", "SUR", "ESTE", "OESTE"], secret: "UN MUNDO POR DESCUBRIR" },
    { theme: "Bebidas", words: ["AGUA", "LECHE", "ZUMO", "VINO", "CERVEZA", "CAFE", "REFRESCO", "TE", "LIMONADA", "HORCHATA"], secret: "LAS COSAS CLARAS Y EL CHOCOLATE ESPESO" },
    { theme: "Meses del Año", words: ["ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE"], secret: "EN ABRIL AGUAS MIL" },
    { theme: "Días de la Semana", words: ["LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO", "AYER", "HOY", "MAÑANA"], secret: "NO DEJES PARA MAÑANA LO QUE PUEDAS HACER HOY" },
    { theme: "Familia", words: ["PADRE", "MADRE", "HIJO", "HIJA", "HERMANO", "HERMANA", "ABUELO", "ABUELA", "TIO", "TIA"], secret: "DE TAL PALO TAL ASTILLA" },
    { theme: "Asignaturas", words: ["MATEMATICAS", "LENGUA", "HISTORIA", "CIENCIA", "GEOGRAFIA", "MUSICA", "ARTE", "FISICA", "QUIMICA", "BIOLOGIA"], secret: "NUNCA TE ACOSTARAS SIN SABER UNA COSA MAS" },
    { theme: "Sentimientos", words: ["AMOR", "ALEGRIA", "TRISTEZA", "MIEDO", "SORPRESA", "ENFADO", "ASCO", "VERGUENZA", "ORGULLO", "ESPERANZA"], secret: "EL CORAZON TIENE RAZONES QUE LA RAZON NO ENTIENDE" },
    { theme: "Animales Marinos", words: ["BALLENA", "DELFIN", "TIBURON", "PULPO", "CANGREJO", "MEDUSA", "FOCA", "TORTUGA", "PEZ", "ESTRELLA"], secret: "HAY MAS PECES EN EL MAR" },
    { theme: "Postres", words: ["TARTA", "HELADO", "FLAN", "NATILLAS", "ARROZ", "LECHE", "YOGUR", "FRUTA", "CHOCOLATE", "GALLETA"], secret: "A NADIE LE AMARGA UN DULCE" },
    { theme: "Materiales de Oficina", words: ["PAPEL", "LAPIZ", "BOLIGRAFO", "GOMA", "REGLA", "TIJERAS", "GRAPADORA", "CLIP", "CARPETA", "FOLIO"], secret: "HACER BUEN PAPEL" },
    { theme: "Planetas del Sistema Solar", words: ["MERCURIO", "VENUS", "TIERRA", "MARTE", "JUPITER", "SATURNO", "URANO", "NEPTUNO", "PLUTON", "SOL"], secret: "ESTAR EN LA LUNA" },
    { theme: "Géneros de Cine", words: ["COMEDIA", "DRAMA", "ACCION", "TERROR", "CIENCIA", "FICCION", "AVENTURA", "MUSICAL", "OESTE", "SUSPENSE"], secret: "LA VIDA ES PURO TEATRO" },
    { theme: "Transportes", words: ["COCHE", "AVION", "BARCO", "TREN", "AUTOBUS", "BICICLETA", "MOTO", "CAMION", "HELICOPTERO", "METRO"], secret: "CADA LOCO CON SU TEMA" },
    { theme: "Monedas", words: ["EURO", "DOLAR", "LIBRA", "YEN", "PESO", "FRANCO", "RUPIA", "YUAN", "RUBLO", "MARCO"], secret: "EL TIEMPO ES ORO" },
    { theme: "Huesos del Cuerpo", words: ["CRANEO", "FEMUR", "TIBIA", "PERONE", "HUMERO", "COSTILLA", "VERTEBRA", "PELVIS", "RADIO", "CUBITO"], secret: "HASTA LOS HUESOS" },
    { theme: "Sabores", words: ["DULCE", "SALADO", "ACIDO", "AMARGO", "PICANTE", "UMAMI", "FRESCO", "CALIENTE", "FRIO", "TEMPLADO"], secret: "PARA GUSTOS LOS COLORES" },
    { theme: "Piedras Preciosas", words: ["DIAMANTE", "RUBI", "ESMERALDA", "ZAFIRO", "OPALO", "AMATISTA", "TOPACIO", "AGUAMARINA", "TURQUESA", "GRANATE"], secret: "MAS VALE PREVENIR QUE CURAR" },
    { theme: "Mitología Griega", words: ["ZEUS", "HERA", "APOLO", "ARTEMISA", "ARES", "ATENEA", "POSEIDON", "HADES", "HERMES", "AFRODITA"], secret: "LA MANZANA DE LA DISCORDIA" },
    { theme: "En el Baño", words: ["DUCHA", "BAÑERA", "LAVABO", "INODORO", "ESPEJO", "TOALLA", "JABON", "CHAMPU", "CEPILLO", "PEINE"], secret: "COMO PEDRO POR SU CASA" },
    { theme: "En el Jardín", words: ["CESPED", "FLOR", "ARBOL", "FUENTE", "BANCO", "CAMINO", "PIEDRA", "TIERRA", "RAIZ", "HOJA"], secret: "NO HAY ROSA SIN ESPINAS" },
    { theme: "En el Supermercado", words: ["CARRO", "CESTA", "CAJA", "PASILLO", "OFERTA", "PRECIO", "PRODUCTO", "CLIENTE", "BOLSA", "COMPRA"], secret: "LO BARATO SALE CARO" },
    { theme: "Clima", words: ["SOLEADO", "NUBLADO", "LLUVIOSO", "VENTOSO", "CALUROSO", "FRIO", "TEMPLADO", "HUMEDO", "SECO", "TROPICAL"], secret: "AL MAL TIEMPO BUENA CARA" },
    { theme: "Formas de Relieve", words: ["MONTAÑA", "VALLE", "LLANURA", "MESETA", "CAÑON", "COLINA", "COSTA", "PLAYA", "ISLA", "PENINSULA"], secret: "MOVER MONTAÑAS" },
    { theme: "Partes de una Casa", words: ["TEJADO", "PARED", "SUELO", "TECHO", "PUERTA", "VENTANA", "COCINA", "SALON", "BAÑO", "DORMITORIO"], secret: "MI CASA ES TU CASA" },
    { theme: "Mamíferos", words: ["PERRO", "GATO", "LEON", "TIGRE", "OSO", "LOBO", "ZORRO", "CIERVO", "JABALI", "ELEFANTE"], secret: "PERRO LADRADOR POCO MORDEDOR" },
    { theme: "Aves", words: ["AGUILA", "HALCON", "BUITRE", "PALOMA", "GORRION", "CANARIO", "LORO", "CUERVO", "CISNE", "FLAMENCO"], secret: "MAS VALE PAJARO EN MANO" },
    { theme: "Reptiles", words: ["SERPIENTE", "LAGARTO", "TORTUGA", "COCODRILO", "CAIMAN", "IGUANA", "SALAMANDRA", "GECKO", "CAMALEON", "DRAGON"], secret: "LAGRIMAS DE COCODRILO" },
    { theme: "Insectos", words: ["HORMIGA", "ABEJA", "MOSCA", "MARIPOSA", "ARAÑA", "ESCARABAJO", "SALTAMONTES", "LIBELULA", "GRILLO", "MARIQUITA"], secret: "POR SI LAS MOSCAS" },
    { theme: "Peces", words: ["ATUN", "SALMON", "SARDINA", "MERLUZA", "DORADA", "LUBINA", "TRUCHA", "BACALAO", "ANCHOA", "BOQUERON"], secret: "POR LA BOCA MUERE EL PEZ" },
    
    // 300 Nuevos Puzzles (1-50)
    { theme: "Tecnología", words: ["COMPUTADORA", "TELEFONO", "INTERNET", "WIFI", "BLUETOOTH", "USB", "PANTALLA", "TECLADO", "RATON", "IMPRESORA"], secret: "LA TECNOLOGIA AVANZA" },
    { theme: "Cocina Internacional", words: ["PAELLA", "PIZZA", "SUSHI", "HAMBURGUESA", "TACOS", "CURRY", "RAMEN", "FALAFEL", "KIMCHI", "MOLE"], secret: "SABORES DEL MUNDO" },
    { theme: "Música Clásica", words: ["SINFONIA", "CONCIERTO", "OPERA", "BALLET", "SONATA", "FUGUE", "ADAGIO", "ALLEGRO", "PRESTO", "LARGO"], secret: "MUSICA ETERNA" },
    { theme: "Arte", words: ["PINTURA", "ESCULTURA", "FOTOGRAFIA", "DIBUJO", "ACUARELA", "OLEO", "CARBONCILLO", "PASTEL", "TINTA", "GRAFITO"], secret: "EL ARTE EXPRESA" },
    { theme: "Literatura", words: ["NOVELA", "POESIA", "CUENTO", "DRAMA", "ENSAYO", "BIOGRAFIA", "FICCION", "REALISMO", "ROMANTICO", "MODERNO"], secret: "LAS PALABRAS VIVEN" },
    { theme: "Cine", words: ["PELICULA", "DIRECTOR", "ACTOR", "ACTRIZ", "GUION", "ESCENA", "PLANO", "MONTAJE", "BANDA", "SONORA"], secret: "LA MAGIA DEL CINE" },
    { theme: "Videojuegos", words: ["CONSOLA", "JOYSTICK", "PANTALLA", "NIVEL", "PUNTUACION", "VIDA", "ENERGIA", "PODER", "MISION", "JEFE"], secret: "JUEGO Y DIVERSION" },
    { theme: "Redes Sociales", words: ["FACEBOOK", "TWITTER", "INSTAGRAM", "YOUTUBE", "TIKTOK", "LINKEDIN", "SNAPCHAT", "WHATSAPP", "TELEGRAM", "DISCORD"], secret: "CONECTADOS SIEMPRE" },
    { theme: "Moda", words: ["VESTIDO", "PANTALON", "CAMISA", "CHAQUETA", "FALDA", "ZAPATOS", "BOLSO", "CINTURON", "CORBATA", "PAÑUELO"], secret: "LA MODA CAMBIA" },
    { theme: "Belleza", words: ["MAQUILLAJE", "CREMA", "CHAMPU", "JABON", "PERFUME", "LACA", "SOMBRA", "RUBOR", "LABIAL", "MASCARILLA"], secret: "BELLEZA NATURAL" },
    { theme: "Fitness", words: ["EJERCICIO", "GIMNASIO", "PESAS", "CARDIO", "YOGURT", "PROTEINA", "VITAMINAS", "MINERALES", "FIBRA", "AGUA"], secret: "SALUD Y VIDA" },
    { theme: "Medicina", words: ["DOCTOR", "ENFERMERA", "HOSPITAL", "MEDICINA", "RECETA", "SINTOMA", "DIAGNOSTICO", "TRATAMIENTO", "CIRUGIA", "CONSULTA"], secret: "LA SALUD PRIMERO" },
    { theme: "Educación", words: ["ESCUELA", "UNIVERSIDAD", "PROFESOR", "ALUMNO", "CLASE", "EXAMEN", "TAREA", "LIBRO", "LAPIZ", "PIZARRA"], secret: "EL CONOCIMIENTO ES PODER" },
    { theme: "Negocios", words: ["EMPRESA", "OFICINA", "REUNION", "PROYECTO", "CLIENTE", "VENTA", "MARKETING", "FINANZAS", "RECURSOS", "ESTRATEGIA"], secret: "EL NEGOCIO CRECE" },
    { theme: "Turismo", words: ["VIAJE", "HOTEL", "AVION", "MALETA", "PASAPORTE", "VISADO", "GUIA", "EXCURSION", "MUSEO", "MONUMENTO"], secret: "EL MUNDO ESPERA" },
    { theme: "Naturaleza", words: ["BOSQUE", "RIO", "LAGO", "MONTAÑA", "PLAYA", "DESIERTO", "JUNGLA", "SAVANA", "TUNDRA", "OCEANO"], secret: "LA NATURALEZA VIVE" },
    { theme: "Clima", words: ["TEMPERATURA", "HUMEDAD", "PRESION", "VIENTO", "NUBE", "PRECIPITACION", "EVAPORACION", "CONDENSACION", "CICLON", "ANTICICLON"], secret: "EL CLIMA CAMBIA" },
    { theme: "Energía", words: ["ELECTRICIDAD", "GASOLINA", "DIESEL", "CARBON", "NUCLEAR", "SOLAR", "EOLICA", "HIDRAULICA", "GEOTERMICA", "BIOMASA"], secret: "ENERGIA LIMPIA" },
    { theme: "Construcción", words: ["CEMENTO", "LADRILLO", "HORMIGON", "ACERO", "MADERA", "VIDRIO", "PLASTICO", "METAL", "PIEDRA", "ARENA"], secret: "CONSTRUIR FUTURO" },
    { theme: "Agricultura", words: ["CULTIVO", "SEMILLA", "FERTILIZANTE", "RIEGO", "COSECHA", "TRACTOR", "SILO", "GRANERO", "INVERNADERO", "PESTICIDA"], secret: "LA TIERRA ALIMENTA" },
    { theme: "Ganadería", words: ["VACA", "CERDO", "OVEJA", "CABRA", "POLLO", "PATO", "GALLINA", "TORO", "CABALLO", "BURRO"], secret: "ANIMALES DE GRANJA" },
    { theme: "Pesca", words: ["PESCADO", "RED", "CAÑA", "CEBO", "ANZUELO", "BARCO", "MAR", "OCEANO", "LAGO", "RIO"], secret: "PESCA SOSTENIBLE" },
    { theme: "Minería", words: ["MINA", "CARBON", "HIERRO", "COBRE", "ORO", "PLATA", "DIAMANTE", "ESMERALDA", "RUBI", "ZAFIRO"], secret: "TESOROS DE LA TIERRA" },
    { theme: "Petróleo", words: ["PETROLEO", "GAS", "REFINERIA", "OLEODUCTO", "PLATAFORMA", "POZO", "CRUDO", "GASOLINA", "DIESEL", "QUEROSENO"], secret: "ENERGIA FOSIL" },
    { theme: "Química", words: ["MOLECULA", "ATOMO", "ELEMENTO", "COMPUESTO", "REACCION", "CATALIZADOR", "SOLUCION", "ACIDO", "BASE", "SAL"], secret: "LA QUIMICA TRANSFORMA" },
    { theme: "Física", words: ["FUERZA", "ENERGIA", "MATERIA", "GRAVEDAD", "ELECTRICIDAD", "MAGNETISMO", "LUZ", "SONIDO", "CALOR", "MOVIMIENTO"], secret: "LAS LEYES DE LA NATURALEZA" },
    { theme: "Biología", words: ["CELULA", "ADN", "GEN", "CROMOSOMA", "PROTEINA", "ENZIMA", "HORMONA", "VITAMINA", "ANTICUERPO", "VACUNA"], secret: "LA VIDA ES BELLA" },
    { theme: "Astronomía", words: ["ESTRELLA", "PLANETA", "GALAXIA", "NEBULOSA", "AGUJERO", "NEGRO", "COMETA", "METEORITO", "CONSTELACION", "ORBITA"], secret: "EL UNIVERSO INFINITO" },
    { theme: "Geología", words: ["ROCA", "MINERAL", "CRISTAL", "FOSIL", "VOLCAN", "TERREMOTO", "EROSION", "SEDIMENTO", "ESTRATO", "PLACA"], secret: "LA TIERRA HABLA" },
    { theme: "Ecología", words: ["ECOSISTEMA", "BIODIVERSIDAD", "CONTAMINACION", "RECICLAJE", "CONSERVACION", "SUSTENTABLE", "RENOVABLE", "ORGANICO", "NATURAL", "VERDE"], secret: "CUIDAR EL PLANETA" },
    { theme: "Psicología", words: ["MENTE", "CONCIENCIA", "MEMORIA", "APRENDIZAJE", "EMOCION", "PERSONALIDAD", "INTELIGENCIA", "CREATIVIDAD", "MOTIVACION", "CONDUCTA"], secret: "LA MENTE ES PODEROSA" },
    { theme: "Filosofía", words: ["VERDAD", "BELLEZA", "BIEN", "MAL", "LIBERTAD", "JUSTICIA", "AMOR", "SABIDURIA", "ETICA", "LOGICA"], secret: "PENSAR ES VIVIR" },
    { theme: "Historia", words: ["PASADO", "PRESENTE", "FUTURO", "CIVILIZACION", "CULTURA", "TRADICION", "REVOLUCION", "GUERRA", "PAZ", "PROGRESO"], secret: "LA HISTORIA SE REPITE" },
    { theme: "Arqueología", words: ["FOSIL", "RUINA", "ARTEFACTO", "MUMMIA", "PIRAMIDE", "TEMPLO", "TUMBA", "CERAMICA", "MONEDA", "INSCRIPCION"], secret: "DESCUBRIR EL PASADO" },
    { theme: "Antropología", words: ["CULTURA", "SOCIEDAD", "TRIBUS", "COSTUMBRES", "RITUALES", "CREENCIAS", "LENGUAJE", "FAMILIA", "COMUNIDAD", "TRADICION"], secret: "LA DIVERSIDAD HUMANA" },
    { theme: "Sociología", words: ["SOCIEDAD", "GRUPO", "COMUNIDAD", "FAMILIA", "EDUCACION", "TRABAJO", "RELIGION", "POLITICA", "ECONOMIA", "CULTURA"], secret: "VIVIR EN SOCIEDAD" },
    { theme: "Economía", words: ["DINERO", "PRECIO", "VALOR", "MERCADO", "OFERTA", "DEMANDA", "INFLACION", "DESEMPLEO", "CRECIMIENTO", "DESARROLLO"], secret: "LA ECONOMIA MUEVE" },
    { theme: "Política", words: ["GOBIERNO", "DEMOCRACIA", "LIBERTAD", "JUSTICIA", "IGUALDAD", "DERECHOS", "DEBERES", "VOTO", "PARTIDO", "LEYES"], secret: "LA POLITICA NOS UNE" },
    { theme: "Derecho", words: ["LEY", "JUSTICIA", "TRIBUNAL", "JUEZ", "ABOGADO", "FISCAL", "DEFENSA", "ACUSACION", "SENTENCIA", "APELACION"], secret: "LA JUSTICIA PREVALECE" },
    { theme: "Religión", words: ["DIOS", "FE", "ORACION", "TEMPLO", "IGLESIA", "SACERDOTE", "BENDICION", "MILAGRO", "SALVACION", "ETERNIDAD"], secret: "LA FE MUEVE MONTAÑAS" },
    { theme: "Mitología", words: ["DIOS", "HEROE", "MONSTRUO", "DRAGON", "FENIX", "UNICORNIO", "SIRENA", "CENTAURO", "MINOTAURO", "HIDRA"], secret: "MITOS Y LEYENDAS" },
    { theme: "Fantasía", words: ["MAGIA", "HECHIZO", "VARITA", "ESCOBA", "CASTILLO", "PRINCESA", "CABALLERO", "DRAGON", "HADA", "DUENDE"], secret: "LA FANTASIA VUELA" },
    { theme: "Ciencia Ficción", words: ["ROBOT", "NAVE", "ESPACIO", "ALIEN", "TECNOLOGIA", "FUTURO", "VIAJE", "TIEMPO", "DIMENSION", "UNIVERSO"], secret: "EL FUTURO ES HOY" },
    { theme: "Misterio", words: ["ENIGMA", "ACERTIJO", "PUZZLE", "CLUE", "PISTA", "SOSPECHOSO", "DETECTIVE", "INVESTIGACION", "CRIMEN", "SOLUCION"], secret: "RESOLVER EL MISTERIO" },
    { theme: "Aventura", words: ["EXPLORACION", "DESCUBRIMIENTO", "RIESGO", "PELIGRO", "VALENTIA", "CORAJE", "HONOR", "GLORIA", "TRIUNFO", "VICTORIA"], secret: "LA AVENTURA LLAMA" },
    { theme: "Romance", words: ["AMOR", "PASION", "ROMANCE", "BESO", "ABRAZO", "CARICIA", "SUSPIRO", "CORAZON", "SENTIMIENTO", "FELICIDAD"], secret: "EL AMOR TODO LO PUEDE" },
    { theme: "Comedia", words: ["RISAS", "HUMOR", "CHISTE", "BROMA", "DIVERSION", "ALEGRIA", "FELICIDAD", "GOZO", "PLACER", "ENTRETENIMIENTO"], secret: "LA RISA ES MEDICINA" },
    { theme: "Tragedia", words: ["DOLOR", "SUFRIMIENTO", "TRISTEZA", "LLANTO", "DESESPERACION", "ANGUSTIA", "PENA", "DUELO", "PERDIDA", "MUERTE"], secret: "EL DOLOR NOS HACE FUERTES" },
    { theme: "Acción", words: ["VELOCIDAD", "FUERZA", "ENERGIA", "MOVIMIENTO", "DINAMISMO", "INTENSIDAD", "POTENCIA", "IMPACTO", "EXPLOSION", "COMBATE"], secret: "LA ACCION NO PARA" },
    { theme: "Suspenso", words: ["TENSION", "NERVIO", "MIEDO", "ANGUSTIA", "SOSPECHA", "INCERTIDUMBRE", "EXPECTATIVA", "SORPRESA", "SHOCK", "IMPACTO"], secret: "EL SUSPENSO MATA" },
    { theme: "Terror", words: ["MIEDO", "HORROR", "PESADILLA", "MONSTRUO", "FANTASMA", "DEMONIO", "OSCURIDAD", "SOMBRA", "CRUJIDO", "GRITO"], secret: "EL MIEDO PARALIZA" },
    { theme: "Western", words: ["VAQUERO", "CABALLO", "PISTOLA", "RIFLE", "SOMBRERO", "BOTAS", "ESPUELAS", "RANCHO", "SALOON", "DUELO"], secret: "EL FAR WEST VIVE" },
    { theme: "Gangster", words: ["MAFIA", "GANSTER", "PISTOLA", "COCHE", "TREN", "DINERO", "PODER", "VIOLENCIA", "CRIMEN", "JUSTICIA"], secret: "LA MAFIA DOMINA" },
    { theme: "Policial", words: ["POLICIA", "DETECTIVE", "INVESTIGACION", "CRIMEN", "SOSPECHOSO", "EVIDENCIA", "PISTA", "INTERROGATORIO", "ARRESTO", "JUSTICIA"], secret: "LA LEY SIEMPRE GANA" },
    { theme: "Espionaje", words: ["ESPIA", "AGENTE", "MISION", "SECRETO", "INFILTRACION", "SABOTAJE", "INTELIGENCIA", "ENCRIPTACION", "DISFRAZ", "PELIGRO"], secret: "EL ESPIONAJE ES ARTE" },
    { theme: "Guerra", words: ["BATALLA", "SOLDADO", "EJERCITO", "ARMA", "BOMBA", "TANQUE", "AVION", "BARCO", "VICTORIA", "DERROTA"], secret: "LA GUERRA DESTRUYE" },
    { theme: "Paz", words: ["ARMONIA", "TRANQUILIDAD", "SERENIDAD", "CALMA", "PAZ", "AMOR", "AMISTAD", "UNION", "FRATERNIDAD", "SOLIDARIDAD"], secret: "LA PAZ ES BELLA" },
    
    // 300 Nuevos Puzzles (51-100)
    { theme: "Deportes Extremos", words: ["PARACAIDISMO", "ESCALADA", "SURF", "SNOWBOARD", "RAFTING", "BUCEO", "ALPINISMO", "KAYAK", "WINDSURF", "PARKOUR"], secret: "ADRENALINA PURA" },
    { theme: "Música Rock", words: ["GUITARRA", "BATERIA", "BAJO", "MICROFONO", "AMPLIFICADOR", "PEDAL", "CABLE", "PICK", "STRAP", "TUNER"], secret: "ROCK AND ROLL" },
    { theme: "Cocina Mexicana", words: ["TACOS", "BURRITO", "ENCHILADA", "QUESADILLA", "GUACAMOLE", "SALSA", "CHILE", "FRIJOLES", "ARROZ", "TORTILLA"], secret: "SABORES MEXICANOS" },
    { theme: "Cocina Italiana", words: ["PIZZA", "PASTA", "LASAGNA", "RISOTTO", "BRUSCHETTA", "TIRAMISU", "GELATO", "PROSCIUTTO", "MOZZARELLA", "PESTO"], secret: "BELLA ITALIA" },
    { theme: "Cocina Japonesa", words: ["SUSHI", "RAMEN", "TEMPURA", "UDON", "SASHIMI", "MISO", "WASABI", "SAKE", "BENTO", "ONIGIRI"], secret: "SABORES DEL SOL NACIENTE" },
    { theme: "Cocina China", words: ["DIMSUM", "WONTON", "CHOWMEIN", "KUNGPAO", "SWEETSOUR", "FRIEDRICE", "DUMPLING", "NOODLES", "STIRFRY", "HOTPOT"], secret: "COCINA MILENARIA" },
    { theme: "Cocina India", words: ["CURRY", "BIRYANI", "NAAN", "TANDOORI", "MASALA", "CHUTNEY", "SAMOSA", "DAL", "ROTI", "KORMA"], secret: "ESPECIAS AROMATICAS" },
    { theme: "Cocina Francesa", words: ["CROISSANT", "BAGUETTE", "QUICHE", "RATATOUILLE", "BOEUF", "ESCARGOT", "FOIEGRAS", "CREPE", "MACARON", "SOUFFLE"], secret: "HAUTE CUISINE" },
    { theme: "Cocina Española", words: ["PAELLA", "TORTILLA", "GAZPACHO", "JAMON", "CHORIZO", "PULPO", "GAMBAS", "ALBONDIGAS", "EMPANADA", "FABADA"], secret: "SABORES DE ESPAÑA" },
    { theme: "Cocina Griega", words: ["MOUSSAKA", "SOUVLAKI", "TZATZIKI", "FETA", "OLIVES", "DOLMADES", "BAKLAVA", "GYROS", "HALOUMI", "TARAMASALATA"], secret: "SABORES HELENICOS" },
    { theme: "Cocina Turca", words: ["KEBAB", "DONER", "LAHMACUN", "PIDE", "BAKLAVA", "TURKISHDELIGHT", "AYRAN", "MANTI", "DOLMA", "IMAMBAYILDI"], secret: "SABORES OTOMANOS" },
    { theme: "Cocina Libanesa", words: ["HUMMUS", "FALAFEL", "TABBOULEH", "SHAWARMA", "FATTOUSH", "MANAKEESH", "KIBBEH", "BAKLAVA", "LABNEH", "ZAATAR"], secret: "SABORES DEL LIBANO" },
    { theme: "Cocina Tailandesa", words: ["PADTHAI", "TOM", "GREENCURRY", "MASSAMAN", "PAPAYASALAD", "SATAY", "PHO", "BANHMI", "SPRINGROLLS", "MANGO"], secret: "SABORES TAILANDESES" },
    { theme: "Cocina Vietnamita", words: ["PHO", "BANHMI", "SPRINGROLLS", "BUNCHA", "CAOPLAU", "COMTOM", "CHA", "GOI", "BANHXEO", "CHE"], secret: "SABORES VIETNAMITAS" },
    { theme: "Cocina Coreana", words: ["BIBIMBAP", "KIMCHI", "BULGOGI", "JAPCHAE", "SAMGYEOPSAL", "TTEOKBOKKI", "SUNDUBU", "HAEMUL", "DOLSOT", "BANCHAN"], secret: "SABORES COREANOS" },
    { theme: "Cocina Marroquí", words: ["COUSCOUS", "TAGINE", "HARIRA", "PASTILLA", "MECHOUI", "KEBAB", "BRIOUAT", "MINTEA", "HALWA", "MSEMEN"], secret: "SABORES MARROQUIES" },
    { theme: "Cocina Egipcia", words: ["KOSHARI", "FUL", "TAAMEYA", "MOLOKHEYA", "MAHSHI", "FATTAH", "UMMALI", "KONAFA", "BASBOUSA", "QATAYEF"], secret: "SABORES EGIPCIOS" },
    { theme: "Cocina Etíope", words: ["INJERA", "WAT", "DORO", "SHIRO", "TIBBS", "KITFO", "AYIB", "BERBERE", "MITMITTA", "NITERKIBBEH"], secret: "SABORES ETIOPES" },
    { theme: "Cocina Sudafricana", words: ["BOEREWORS", "BILLTONG", "BOBOTIE", "POTJIEKOS", "CHAKALAKA", "UMNGQUSHO", "MALVA", "KOESISTERS", "VETKOEK", "AMAGWINYA"], secret: "SABORES SUDAFRICANOS" },
    { theme: "Cocina Brasileña", words: ["FEIJOADA", "CHURRASCO", "MOQUECA", "VATAPA", "ACARAJE", "BRIGADEIRO", "CAIPIRINHA", "PICANHA", "FAROFA", "COXINHA"], secret: "SABORES BRASILEÑOS" },
    { theme: "Cocina Argentina", words: ["ASADO", "EMPANADA", "MILANESA", "LOCRO", "CHIMICHURRI", "DULCEDELECHE", "ALFAJOR", "MATE", "PROVOLETA", "CHORIPAN"], secret: "SABORES ARGENTINOS" },
    { theme: "Cocina Peruana", words: ["CEVICHE", "LOMO", "AJIDEGALLINA", "CAUSA", "ANTICUCHO", "ROCOTO", "CHUPE", "PICARONES", "CHICHA", "PISCO"], secret: "SABORES PERUANOS" },
    { theme: "Cocina Colombiana", words: ["BANDEJAPAISA", "AJIACO", "SANCOCHO", "EMPANADA", "AREPAS", "CHICHARRON", "LECHONA", "TAMALES", "BUÑUELOS", "NATILLA"], secret: "SABORES COLOMBIANOS" },
    { theme: "Cocina Venezolana", words: ["AREAPA", "PABELLON", "HALLACA", "CACHAPA", "EMPANADA", "TEQUEÑOS", "ASADO", "QUESILLO", "MAJARETE", "CHICHA"], secret: "SABORES VENEZOLANOS" },
    { theme: "Cocina Ecuatoriana", words: ["CEVICHE", "ENCURTIDO", "FANESCA", "LOCRO", "HORNADO", "LLAPINGACHOS", "EMPANADA", "QUIMBOLITOS", "COLADA", "CHICHA"], secret: "SABORES ECUATORIANOS" },
    { theme: "Cocina Chilena", words: ["EMPANADA", "PASTEL", "CURANTO", "CHUPE", "CAZUELA", "POROTOS", "HUMITAS", "SOPAIPILLAS", "ALFAJORES", "CHICHA"], secret: "SABORES CHILENOS" },
    { theme: "Cocina Uruguaya", words: ["ASADO", "CHIVITO", "EMPANADA", "MILANESA", "PASTA", "GNOCCHI", "DULCEDELECHE", "ALFAJOR", "MATE", "GRAFFIGNAC"], secret: "SABORES URUGUAYOS" },
    { theme: "Cocina Paraguaya", words: ["CHIPAGUAZU", "SOPA", "MBEYU", "PASTEL", "EMPANADA", "CHIPA", "ASADO", "MATE", "TERERE", "CAÑA"], secret: "SABORES PARAGUAYOS" },
    { theme: "Cocina Boliviana", words: ["SALTEÑA", "SILPANCHO", "PICANTE", "CHICHARRON", "LECHON", "AJI", "CHUÑO", "QUINOA", "COCA", "SINGANI"], secret: "SABORES BOLIVIANOS" },
    { theme: "Cocina Panameña", words: ["SANCOCHO", "ROPAVIEJA", "TAMALES", "EMPANADA", "HOJALDRE", "ARROZ", "POLLO", "CEVICHE", "CHICHA", "RON"], secret: "SABORES PANAMEÑOS" },
    { theme: "Cocina Costarricense", words: ["GALLOPINTO", "CASADO", "CHIFRIJO", "CEVICHE", "TAMALES", "EMPANADA", "CHORREADA", "CHICHA", "CAFÉ", "GUARO"], secret: "SABORES COSTARRICENSES" },
    { theme: "Cocina Nicaragüense", words: ["GALLOPINTO", "NACATAMAL", "VIGORON", "INDIO", "QUESILLO", "TACOS", "CHICHARRON", "CHICHA", "RON", "CAFÉ"], secret: "SABORES NICARAGÜENSES" },
    { theme: "Cocina Hondureña", words: ["BALEADA", "PLATO", "SOPA", "TAMALES", "EMPANADA", "CHICHARRON", "YUCA", "CHICHA", "RON", "CAFÉ"], secret: "SABORES HONDUREÑOS" },
    { theme: "Cocina Guatemalteca", words: ["TAMALES", "CHILES", "RELLENOS", "EMPANADA", "CHICHARRON", "YUCA", "CHICHA", "RON", "CAFÉ", "CHOCOLATE"], secret: "SABORES GUATEMALTECOS" },
    { theme: "Cocina Salvadoreña", words: ["PUPUSAS", "TAMALES", "EMPANADA", "YUCA", "CHICHARRON", "CHICHA", "RON", "CAFÉ", "CHOCOLATE", "ATOL"], secret: "SABORES SALVADOREÑOS" },
    { theme: "Cocina Beliceña", words: ["RICE", "BEANS", "STEW", "CHICKEN", "FISH", "LOBSTER", "CONCH", "CAFÉ", "RUM", "CHOCOLATE"], secret: "SABORES BELICEÑOS" },
    { theme: "Cocina Caribeña", words: ["JERK", "CURRY", "ROTI", "DOUBLES", "PELAU", "COUCOU", "FUNGI", "RUM", "COCONUT", "MANGO"], secret: "SABORES CARIBEÑOS" },
    { theme: "Cocina Jamaicana", words: ["JERK", "CURRY", "ROTI", "ACKEE", "SALT", "FISH", "RUM", "COCONUT", "MANGO", "BANANA"], secret: "SABORES JAMAICANOS" },
    { theme: "Cocina Haitiana", words: ["GRIOT", "RICE", "BEANS", "STEW", "CHICKEN", "FISH", "RUM", "COCONUT", "MANGO", "BANANA"], secret: "SABORES HAITIANOS" },
    { theme: "Cocina Dominicana", words: ["SANCOCHO", "MANGU", "CHICHARRON", "EMPANADA", "ARROZ", "POLLO", "RUM", "COCONUT", "MANGO", "BANANA"], secret: "SABORES DOMINICANOS" },
    { theme: "Cocina Puertorriqueña", words: ["MOFONGO", "ARROZ", "GANDULES", "EMPANADA", "CHICHARRON", "RUM", "COCONUT", "MANGO", "BANANA", "PLATANO"], secret: "SABORES PUERTORRIQUEÑOS" },
    { theme: "Cocina Cubana", words: ["ROPAVIEJA", "ARROZ", "FRIJOLES", "EMPANADA", "CHICHARRON", "RUM", "COCONUT", "MANGO", "BANANA", "PLATANO"], secret: "SABORES CUBANOS" },
    { theme: "Cocina Mexicana Regional", words: ["MOLE", "POZOLE", "CHILES", "ENNOGADA", "COCHINITA", "PIBIL", "CABRITO", "CHILAQUILES", "MENUDO", "BIRRIA"], secret: "SABORES REGIONALES" },
    { theme: "Cocina Tex-Mex", words: ["FAJITAS", "NACHOS", "QUESADILLA", "BURRITO", "TACOS", "CHILI", "ENCHILADA", "TAMALES", "GUACAMOLE", "SALSA"], secret: "SABORES TEX-MEX" },
    { theme: "Cocina Cajún", words: ["GUMBO", "JAMBALAYA", "ETOUFFEE", "CRAWFISH", "BOIL", "POBOY", "BOUCHERIE", "BOUDAIN", "CRACKLINS", "BOUDAIN"], secret: "SABORES CAJUN" },
    { theme: "Cocina Creole", words: ["GUMBO", "JAMBALAYA", "ETOUFFEE", "CRAWFISH", "BOIL", "POBOY", "BOUCHERIE", "BOUDAIN", "CRACKLINS", "BOUDAIN"], secret: "SABORES CREOLE" },
    { theme: "Cocina Soul Food", words: ["FRIEDCHICKEN", "COLLARDS", "MACARONI", "CHEESE", "CORNbread", "BLACKEYED", "PEAS", "SWEETPOTATO", "PIE", "CHITLINS"], secret: "SABORES SOUL" },
    { theme: "Cocina Amish", words: ["CHICKEN", "POTPIE", "SHOOFLY", "PIE", "APPLE", "BUTTER", "SCRAPPLE", "CHOWCHOW", "PICKLED", "EGGS"], secret: "SABORES AMISH" },
    { theme: "Cocina Mennonite", words: ["CHICKEN", "POTPIE", "SHOOFLY", "PIE", "APPLE", "BUTTER", "SCRAPPLE", "CHOWCHOW", "PICKLED", "EGGS"], secret: "SABORES MENNONITE" },
    { theme: "Cocina Pennsylvania Dutch", words: ["CHICKEN", "POTPIE", "SHOOFLY", "PIE", "APPLE", "BUTTER", "SCRAPPLE", "CHOWCHOW", "PICKLED", "EGGS"], secret: "SABORES PENNSYLVANIA DUTCH" },
    { theme: "Cocina New England", words: ["CLAMCHOWDER", "LOBSTER", "ROLL", "CRANBERRY", "SAUCE", "PUMPKIN", "PIE", "APPLE", "CIDER", "MAPLE", "SYRUP"], secret: "SABORES NEW ENGLAND" },
    { theme: "Cocina Southern", words: ["FRIEDCHICKEN", "COLLARDS", "MACARONI", "CHEESE", "CORNbread", "BLACKEYED", "PEAS", "SWEETPOTATO", "PIE", "CHITLINS"], secret: "SABORES SOUTHERN" },
    { theme: "Cocina Midwestern", words: ["CASSEROLE", "HOTDISH", "JELLO", "SALAD", "POTATO", "SALAD", "DEVILED", "EGGS", "AMBROSIA", "SALAD", "FUNERAL"], secret: "SABORES MIDWESTERN" },
    { theme: "Cocina Southwestern", words: ["CHILI", "TACOS", "ENCHILADA", "TAMALES", "GUACAMOLE", "SALSA", "QUESADILLA", "BURRITO", "FAJITAS", "NACHOS"], secret: "SABORES SOUTHWESTERN" },
    { theme: "Cocina Pacific Northwest", words: ["SALMON", "CRAB", "OYSTERS", "CLAMS", "MUSSELS", "BERRIES", "APPLES", "CHERRIES", "PEARS", "PLUMS"], secret: "SABORES PACIFIC NORTHWEST" },
    { theme: "Cocina Californiana", words: ["AVOCADO", "TOAST", "SUSHI", "BURRITO", "TACOS", "PIZZA", "SALAD", "SMOOTHIE", "ACAI", "BOWL"], secret: "SABORES CALIFORNIANOS" },
    { theme: "Cocina Hawaiiana", words: ["POI", "KALUA", "PIG", "LAULAU", "POKE", "SPAM", "MUSUBI", "SHAVE", "ICE", "MAI", "TAI"], secret: "SABORES HAWAIIANOS" },
    { theme: "Cocina Alaskana", words: ["SALMON", "CRAB", "HALIBUT", "CARIBOU", "MOOSE", "BERRIES", "WILD", "RICE", "MAPLE", "SYRUP"], secret: "SABORES ALASKANOS" },
    { theme: "Cocina Canadiense", words: ["POUTINE", "MAPLE", "SYRUP", "BUTTER", "TARTS", "NANIMO", "BARS", "BEAVERTAILS", "KRAFT", "DINNER"], secret: "SABORES CANADIENSES" },
    { theme: "Cocina Quebequense", words: ["POUTINE", "MAPLE", "SYRUP", "BUTTER", "TARTS", "NANIMO", "BARS", "BEAVERTAILS", "KRAFT", "DINNER"], secret: "SABORES QUEBEQUENSES" },
    { theme: "Cocina Acadiana", words: ["GUMBO", "JAMBALAYA", "ETOUFFEE", "CRAWFISH", "BOIL", "POBOY", "BOUCHERIE", "BOUDAIN", "CRACKLINS", "BOUDAIN"], secret: "SABORES ACADIANOS" },
    { theme: "Cocina Newfoundland", words: ["FISH", "CHIPS", "COD", "CAKES", "SCREECH", "RUM", "BLUEBERRY", "PIE", "PARTIDGE", "BERRY"], secret: "SABORES NEWFOUNDLAND" },
    { theme: "Cocina Marítima", words: ["LOBSTER", "CRAB", "CLAMS", "MUSSELS", "OYSTERS", "SCALLOPS", "HADDOCK", "COD", "SALMON", "TROUT"], secret: "SABORES MARITIMOS" },
    { theme: "Cocina Pradera", words: ["BISON", "WILD", "RICE", "BERRIES", "MAPLE", "SYRUP", "CORN", "BEANS", "SQUASH", "PUMPKIN"], secret: "SABORES PRAdera" },
    { theme: "Cocina Montaña", words: ["TROUT", "ELK", "DEER", "BERRIES", "MUSHROOMS", "WILD", "RICE", "MAPLE", "SYRUP", "HONEY"], secret: "SABORES MONTAÑA" },
    { theme: "Cocina Costa Oeste", words: ["SALMON", "CRAB", "OYSTERS", "CLAMS", "MUSSELS", "BERRIES", "APPLES", "CHERRIES", "PEARS", "PLUMS"], secret: "SABORES COSTA OESTE" },
    { theme: "Cocina Costa Este", words: ["LOBSTER", "CRAB", "CLAMS", "MUSSELS", "OYSTERS", "SCALLOPS", "HADDOCK", "COD", "SALMON", "TROUT"], secret: "SABORES COSTA ESTE" },
    { theme: "Cocina Interior", words: ["BEEF", "PORK", "CHICKEN", "CORN", "BEANS", "SQUASH", "PUMPKIN", "APPLES", "BERRIES", "MAPLE"], secret: "SABORES INTERIOR" },
    { theme: "Cocina Norteña", words: ["FISH", "GAME", "BERRIES", "MUSHROOMS", "WILD", "RICE", "MAPLE", "SYRUP", "HONEY", "NUTS"], secret: "SABORES NORTEÑOS" },
    { theme: "Cocina Sureña", words: ["FRIEDCHICKEN", "COLLARDS", "MACARONI", "CHEESE", "CORNbread", "BLACKEYED", "PEAS", "SWEETPOTATO", "PIE", "CHITLINS"], secret: "SABORES SUREÑOS" },
    { theme: "Cocina Occidental", words: ["BEEF", "PORK", "CHICKEN", "CORN", "BEANS", "SQUASH", "PUMPKIN", "APPLES", "BERRIES", "MAPLE"], secret: "SABORES OCCIDENTALES" },
    { theme: "Cocina Oriental", words: ["FISH", "RICE", "NOODLES", "SOY", "SAUCE", "MISO", "WASABI", "SAKE", "TEA", "GINGER"], secret: "SABORES ORIENTALES" },
    { theme: "Cocina Central", words: ["BEEF", "PORK", "CHICKEN", "CORN", "BEANS", "SQUASH", "PUMPKIN", "APPLES", "BERRIES", "MAPLE"], secret: "SABORES CENTRALES" },
    { theme: "Cocina Septentrional", words: ["FISH", "GAME", "BERRIES", "MUSHROOMS", "WILD", "RICE", "MAPLE", "SYRUP", "HONEY", "NUTS"], secret: "SABORES SEPTENTRIONALES" },
    { theme: "Cocina Meridional", words: ["FRIEDCHICKEN", "COLLARDS", "MACARONI", "CHEESE", "CORNbread", "BLACKEYED", "PEAS", "SWEETPOTATO", "PIE", "CHITLINS"], secret: "SABORES MERIDIONALES" }
];
// --- END PUZZLE DATA ---

export default puzzles;