// --- START PUZZLE DATA ---
export const puzzles = [
    // Originales
    { theme: "Colores", words: ["ROJO", "AZUL", "VERDE", "AMARILLO", "NARANJA", "VIOLETA", "BLANCO", "NEGRO", "TURQUESA", "MAGENTA"], secret: "EL SABER NO OCUPA LUGAR" },
    { theme: "Frutas", words: ["MANZANA", "PLATANO", "FRESA", "NARANJA", "UVA", "PERA", "LIMON", "SANDIA", "MELOCOTON", "KIWI"], secret: "A BUEN HAMBRE NO HAY PAN DURO" },
    { theme: "Animales", words: ["VACA", "CERDO", "CABALLO", "OVEJA", "GALLINA", "PATO", "CONEJO", "TORO", "ELEFANTE", "JIRAFA"], secret: "MAS VALE PAJARO EN MANO" },
    { theme: "Cuerpo Humano", words: ["CABEZA", "BRAZO", "PIERNA", "MANO", "OJO", "BOCA", "NARIZ", "OREJA", "HOMBRO", "RODILLA"], secret: "OJOS QUE NO VEN CORAZON QUE NO SIENTE" },
    
    // 50 Nuevos Puzzles
    { theme: "El Espacio", words: ["PLANETA", "ESTRELLA", "GALAXIA", "COMETA", "LUNA", "SOL", "NEBULOSA", "ASTEROIDE", "ORBITA", "COHETE"], secret: "DE OTRO MUNDO" },
    { theme: "Instrumentos Musicales", words: ["GUITARRA", "PIANO", "VIOLIN", "TROMPETA", "BATERIA", "FLAUTA", "SAXOFON", "ARPA", "BAJO", "CLARINETE"], secret: "LA MUSICA AMANSA A LAS FIERAS" },
    { theme: "Deportes", words: ["FUTBOL", "BALONCESTO", "TENIS", "NATACION", "ATLETISMO", "BOXEO", "CICLISMO", "GOLF", "VOLEIBOL", "ESGRIMA"], secret: "LO IMPORTANTE ES PARTICIPAR" },
    { theme: "Mobiliario", words: ["SILLA", "MESA", "CAMA", "ARMARIO", "SOFA", "ESTANTERIA", "ESCRITORIO", "COMODA", "VITRINA", "TABURETE"], secret: "CADA COSA EN SU LUGAR" },
    { theme: "Profesiones", words: ["MEDICO", "PROFESOR", "BOMBERO", "POLICIA", "INGENIERO", "ABOGADO", "COCINERO", "PERIODISTA", "CARPINTERO", "PINTOR"], secret: "ZAPATERO A TUS ZAPATOS" },
    { theme: "Países de Europa", words: ["ESPAÑA", "FRANCIA", "ITALIA", "ALEMANIA", "PORTUGAL", "GRECIA", "SUECIA", "NORUEGA", "FINLANDIA", "POLONIA"], secret: "TODOS LOS CAMINOS LLEVAN A ROMA" },
    { theme: "Herramientas", words: ["MARTILLO", "BROCHA", "SIERRA", "ALICATES", "LLAVE", "TALADRO", "TORNILLO", "CLAVO", "CINCEL", "ESPATULA"], secret: "QUIEN TIENE UN OFICIO TIENE UN BENEFICIO" },
    { theme: "En la Cocina", words: ["CUCHILLO", "TENEDOR", "CUCHARA", "PLATO", "VASO", "SARTEN", "OLLA", "HORNO", "NEVERA", "FUEGO"], secret: "A FUEGO LENTO" },
    { theme: "Fenómenos Meteorológicos", words: ["LLUVIA", "NIEVE", "VIENTO", "TORMENTA", "GRANIZO", "NIEBLA", "HURACAN", "TORNADO", "ARCOIRIS", "RAYO"], secret: "DESPUES DE LA TEMPESTAD VIENE LA CALMA" },
    { theme: "Partes de un Coche", words: ["MOTOR", "RUEDA", "VOLANTE", "FRENO", "ASIENTO", "PUERTA", "VENTANA", "MALETERO", "FARO", "PARACHOQUES"], secret: "SOBRE RUEDAS" },
    { theme: "Flores", words: ["ROSA", "CLAVEL", "MARGARITA", "TULIPAN", "GIRASOL", "LIRIO", "ORQUIDEA", "JAZMIN", "VIOLETA", "AMAPOLA"], secret: "LA PRIMAVERA LA SANGRE ALTERA" },
    { theme: "Ropa", words: ["CAMISETA", "PANTALON", "VESTIDO", "FALDA", "CHAQUETA", "ABRIGO", "SOMBRERO", "ZAPATOS", "GUANTES", "BUFANDA"], secret: "EL HABITO NO HACE AL MONJE" },
    { theme: "Árboles", words: ["ROBLE", "PINO", "CAOBA", "CEDRO", "ABETO", "OLIVO", "ALMENDRO", "CEREZO", "NOGAL", "CASTAÑO"], secret: "ARBOL QUE NACE TORCIDO JAMAS SU TRONCO ENDEREZA" },
    { theme: "Verduras", words: ["TOMATE", "LECHUGA", "ZANAHORIA", "PATATA", "CEBOLLA", "PIMIENTO", "ESPINACA", "BROCOLI", "CALABAZA", "PEPINO"], secret: "SANO COMO UNA MANZANA" },
    { theme: "Capitales del Mundo", words: ["MADRID", "PARIS", "LONDRES", "ROMA", "BERLIN", "LISBOA", "ATENAS", "MOSCU", "TOKIO", "PEKIN"], secret: "PREGUNTANDO SE LLEGA A ROMA" },
    { theme: "Elementos Químicos", words: ["HIDROGENO", "HELIO", "OXIGENO", "CARBONO", "HIERRO", "ORO", "PLATA", "COBRE", "SODIO", "POTASIO"], secret: "LA FORMULA SECRETA" },
    { theme: "Figuras Geométricas", words: ["CIRCULO", "CUADRAD", "TRIANGULO", "RECTANGULO", "ROMBO", "PENTAGONO", "HEXAGONO", "OVALO", "CUBO", "ESFERA"], secret: "TODO ENCAJA" },
    { theme: "Continentes", words: ["ASIA", "AFRICA", "EUROPA", "AMERICA", "OCEANIA", "ANTARTIDA", "NORTE", "SUR", "ESTE", "OESTE"], secret: "UN MUNDO POR DESCUBRIR" },
    { theme: "Bebidas", words: ["AGUA", "LECHE", "ZUMO", "VINO", "CERVEZA", "CAFE", "REFRESCO", "TE", "LIMONADA", "HORCHATA"], secret: "LAS COSAS CLARAS Y EL CHOCOLATE ESPESO" },
    { theme: "Meses del Año", words: ["ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE"], secret: "EN ABRIL AGUAS MIL" },
    { theme: "Días de la Semana", words: ["LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO", "AYER", "HOY", "MAÑANA"], secret: "NO DEJES PARA MAÑANA LO QUE PUEDAS HACER HOY" },
    { theme: "Familia", words: ["PADRE", "MADRE", "HIJO", "HIJA", "HERMANO", "HERMANA", "ABUELO", "ABUELA", "TIO", "TIA"], secret: "DE TAL PALO TAL ASTILLA" },
    { theme: "Asignaturas", words: ["MATEMATICAS", "LENGUA", "HISTORIA", "CIENCIA", "GEOGRAFIA", "MUSICA", "ARTE", "FISICA", "QUIMICA", "BIOLOGIA"], secret: "NUNCA TE ACOSTARAS SIN SABER UNA COSA MAS" },
    { theme: "Sentimientos", words: ["AMOR", "ALEGRIA", "TRISTEZA", "MIEDO", "SORPRESA", "ENFADO", "ASCO", "VERGUENZA", "ORGULLO", "ESPERANZA"], secret: "EL CORAZON TIENE RAZONES QUE LA RAZON NO ENTIENDE" },
    { theme: "Animales Marinos", words: ["BALLENA", "DELFIN", "TIBURON", "PULPO", "CANGREJO", "MEDUSA", "FOCA", "TORTUGA", "PEZ", "ESTRELLA"], secret: "HAY MAS PECES EN EL MAR" },
    { theme: "Postres", words: ["TARTA", "HELADO", "FLAN", "NATILLAS", "ARROZ", "LECHE", "YOGUR", "FRUTA", "CHOCOLATE", "GALLETA"], secret: "A NADIE LE AMARGA UN DULCE" },
    { theme: "Materiales de Oficina", words: ["PAPEL", "LAPIZ", "BOLIGRAFO", "GOMA", "REGLA", "TIJERAS", "GRAPADORA", "CLIP", "CARPETA", "FOLIO"], secret: "HACER BUEN PAPEL" },
    { theme: "Planetas del Sistema Solar", words: ["MERCURIO", "VENUS", "TIERRA", "MARTE", "JUPITER", "SATURNO", "URANO", "NEPTUNO", "PLUTON", "SOL"], secret: "ESTAR EN LA LUNA" },
    { theme: "Géneros de Cine", words: ["COMEDIA", "DRAMA", "ACCION", "TERROR", "CIENCIA", "FICCION", "AVENTURA", "MUSICAL", "OESTE", "SUSPENSE"], secret: "LA VIDA ES PURO TEATRO" },
    { theme: "Transportes", words: ["COCHE", "AVION", "BARCO", "TREN", "AUTOBUS", "BICICLETA", "MOTO", "CAMION", "HELICOPTERO", "METRO"], secret: "CADA LOCO CON SU TEMA" },
    { theme: "Monedas", words: ["EURO", "DOLAR", "LIBRA", "YEN", "PESO", "FRANCO", "RUPIA", "YUAN", "RUBLO", "MARCO"], secret: "EL TIEMPO ES ORO" },
    { theme: "Huesos del Cuerpo", words: ["CRANEO", "FEMUR", "TIBIA", "PERONE", "HUMERO", "COSTILLA", "VERTEBRA", "PELVIS", "RADIO", "CUBITO"], secret: "HASTA LOS HUESOS" },
    { theme: "Sabores", words: ["DULCE", "SALADO", "ACIDO", "AMARGO", "PICANTE", "UMAMI", "FRESCO", "CALIENTE", "FRIO", "TEMPLADO"], secret: "PARA GUSTOS LOS COLORES" },
    { theme: "Piedras Preciosas", words: ["DIAMANTE", "RUBI", "ESMERALDA", "ZAFIRO", "OPALO", "AMATISTA", "TOPACIO", "AGUAMARINA", "TURQUESA", "GRANATE"], secret: "MAS VALE PREVENIR QUE CURAR" },
    { theme: "Mitología Griega", words: ["ZEUS", "HERA", "APOLO", "ARTEMISA", "ARES", "ATENEA", "POSEIDON", "HADES", "HERMES", "AFRODITA"], secret: "LA MANZANA DE LA DISCORDIA" },
    { theme: "En el Baño", words: ["DUCHA", "BAÑERA", "LAVABO", "INODORO", "ESPEJO", "TOALLA", "JABON", "CHAMPU", "CEPILLO", "PEINE"], secret: "COMO PEDRO POR SU CASA" },
    { theme: "En el Jardín", words: ["CESPED", "FLOR", "ARBOL", "FUENTE", "BANCO", "CAMINO", "PIEDRA", "TIERRA", "RAIZ", "HOJA"], secret: "NO HAY ROSA SIN ESPINAS" },
    { theme: "En el Supermercado", words: ["CARRO", "CESTA", "CAJA", "PASILLO", "OFERTA", "PRECIO", "PRODUCTO", "CLIENTE", "BOLSA", "COMPRA"], secret: "LO BARATO SALE CARO" },
    { theme: "Clima", words: ["SOLEADO", "NUBLADO", "LLUVIOSO", "VENTOSO", "CALUROSO", "FRIO", "TEMPLADO", "HUMEDO", "SECO", "TROPICAL"], secret: "AL MAL TIEMPO BUENA CARA" },
    { theme: "Formas de Relieve", words: ["MONTAÑA", "VALLE", "LLANURA", "MESETA", "CAÑON", "COLINA", "COSTA", "PLAYA", "ISLA", "PENINSULA"], secret: "MOVER MONTAÑAS" },
    { theme: "Partes de una Casa", words: ["TEJADO", "PARED", "SUELO", "TECHO", "PUERTA", "VENTANA", "COCINA", "SALON", "BAÑO", "DORMITORIO"], secret: "MI CASA ES TU CASA" },
    { theme: "Mamíferos", words: ["PERRO", "GATO", "LEON", "TIGRE", "OSO", "LOBO", "ZORRO", "CIERVO", "JABALI", "ELEFANTE"], secret: "PERRO LADRADOR POCO MORDEDOR" },
    { theme: "Aves", words: ["AGUILA", "HALCON", "BUITRE", "PALOMA", "GORRION", "CANARIO", "LORO", "CUERVO", "CISNE", "FLAMENCO"], secret: "MAS VALE PAJARO EN MANO" },
    { theme: "Reptiles", words: ["SERPIENTE", "LAGARTO", "TORTUGA", "COCODRILO", "CAIMAN", "IGUANA", "SALAMANDRA", "GECKO", "CAMALEON", "DRAGON"], secret: "LAGRIMAS DE COCODRILO" },
    { theme: "Insectos", words: ["HORMIGA", "ABEJA", "MOSCA", "MARIPOSA", "ARAÑA", "ESCARABAJO", "SALTAMONTES", "LIBELULA", "GRILLO", "MARIQUITA"], secret: "POR SI LAS MOSCAS" },
    { theme: "Peces", words: ["ATUN", "SALMON", "SARDINA", "MERLUZA", "DORADA", "LUBINA", "TRUCHA", "BACALAO", "ANCHOA", "BOQUERON"], secret: "POR LA BOCA MUERE EL PEZ" },
];
// --- END PUZZLE DATA ---

export default puzzles;